#!/usr/bin/env python3
"""Numerical checks for the core fixed-budget theory items TH-1 and TH-2 (no new simulation).

Reads stored material only:
  * the theory-scout Feynman-Kac (FK) ensembles of UNKILLED Euler-Maruyama paths
    (2e5 paths each, dt = 1e-3, production parameters, equal weights; generated by
    notes/gap_diagnosis_20260923/theory_scout/fk_paths.py with seeds 11..16, the seed
    is re-read from each file), default location ~/.local-build/prr_gap_fk_cache/;
    each file stores the per-walker cumulative unit-budget exposure X at the
    checkpoints (0.5, free-mixture valleys, 3.5, 4.0), per-slab exposures, the mean
    rate G on the time grid and the exact FK reaction probability per step;
  * the W1 phase-diagram histograms (direct-kill simulator, 1e6 walkers) and the D1
    free-clock valleys, for the sign of the basin-1 mean-field bias.

Checks (all deterministic post-processing):
  TH-1  sandwich e^{-B Lam} <= S_B <= e^{-B Lam} + B^2 h(B Lam) Var X at every checkpoint
        and budget (exact for the empirical law; the informative output is the
        tightness gap/bound), CDF dominance P(T <= t) <= 1 - e^{-B Lam(t)} on the time grid,
        basin-mass bracketing exact - mean-field in [-delta(cut_right), +delta(cut_left)]
        (flag bracket_var_holds, variance-based bounds; flag bracket_holds is the weaker
        gap-identity consistency check with the empirical Jensen gaps).
  TH-2  Var X at the basin cuts versus eps D0/(2 sqrt(pi) rho) sum_{i<=j} k_i^2/v_i^3
        (free kernel, k_i = w_i/W^{d-1}); exact FK basin masses versus the stick-breaking
        limit; local peak heights eps*max f versus the exact limit profile
        S_{j-1}(v_j/rho) max F_beta and the mean-field limit profile S_{j-1}(v_j/S) max p_beta.

Output: artifacts/data/exact_m_fixed_budget/TH_core/theory_core_checks.json
(item folder TH_core = the core theory bundle TH-1, TH-2, TH-4, TH-9)
"""

from __future__ import annotations

import argparse
import glob
import json
import math
import os
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent))

import exact_m_prr_upgrade_core as core  # noqa: E402

FK_CACHE_DEFAULT = Path.home() / ".local-build" / "prr_gap_fk_cache"
OUT_JSON = core.REPORT / "artifacts" / "data" / "exact_m_fixed_budget" / "TH_core" / "theory_core_checks.json"
CASES = [(2, 0.1), (2, 0.05), (2, 0.035), (3, 0.1), (3, 0.05), (3, 0.035)]


def h_fun(u: np.ndarray | float) -> np.ndarray:
    """h(u) = int_0^1 r e^{-r u} dr = (1 - (1+u) e^{-u})/u^2, h(0) = 1/2."""
    u = np.asarray(u, float)
    out = np.empty_like(u)
    small = u < 1e-4
    out[small] = 0.5 - u[small] / 3.0 + u[small] ** 2 / 8.0
    ub = u[~small]
    out[~small] = -np.expm1(-ub) / ub**2 - np.exp(-ub) / ub
    return out


def phi(x):
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def Phi(x):
    from math import erf

    return 0.5 * (1.0 + np.vectorize(erf)(np.asarray(x) / math.sqrt(2.0)))


def limit_profile_peaks(beta: float, lam: float) -> dict:
    """max of F_beta = p_beta * phi_lam (exact limit) and of p_beta (mean-field limit)."""
    u = np.linspace(-14.0, 14.0, 28001)
    du = u[1] - u[0]
    pb = beta * phi(u) * np.exp(-beta * Phi(u))
    kern = phi(u / lam) / lam
    fb = np.convolve(pb, kern, mode="same") * du
    return {"beta": beta, "max_F_beta": float(fb.max()), "argmax_F_beta": float(u[int(np.argmax(fb))]),
            "max_p_beta": float(pb.max()), "argmax_p_beta": float(u[int(np.argmax(pb))]),
            "mass_F_beta": float(fb.sum() * du), "mass_expected": float(-math.expm1(-beta))}


def analyse_case(path: Path, p) -> dict:
    d = np.load(path)
    m, eps, dt = int(d["m"]), float(d["eps"]), float(d["dt"])
    budgets = np.asarray(d["budgets"], float)
    w = np.asarray(d["weights"], float)
    tt = core.TARGET_TIMES[m]
    v = np.array([p.gamma * abs(p.z0 - p.z_bar) * math.exp(-p.gamma * t) for t in tt])
    area = p.torus_w ** (p.dim - 1)
    k = w / area
    s_star = math.sqrt(p.d0 / (2 * p.gamma) + p.rho**2)
    lam_ratio = math.sqrt(p.d0 / (2 * p.gamma)) / p.rho
    ck = np.asarray(d["checkpoints"], float)
    n_cut = m + 1  # cuts: 0.5, valleys (m-1), 3.5
    out = {"file": str(path), "seed": int(d["seed"]), "N": int(d["N"]), "m": m, "eps": eps, "dt": dt,
           "checkpoints": ck.tolist(), "budgets": budgets.tolist(), "weights": w.tolist(), "speeds_v": v.tolist()}
    kern_out = {}
    for kern in ("full", "free"):
        X = np.asarray(d[f"lamck_{kern}"], float)
        N = X.shape[0]
        lam_hat = X.mean(axis=0)
        var_hat = X.var(axis=0, ddof=1)
        rows = []
        cols = [np.ascontiguousarray(X[:, c]) for c in range(X.shape[1])]
        for b in budgets:
            eb = np.exp(-b * X)
            mf = np.exp(-b * lam_hat)
            # Jensen gap evaluated without cancellation: e^{-B Lam} mean(expm1(-B (X - Lam)))
            gap = np.array([mf[c] * float(np.mean(np.expm1(-b * (cols[c] - lam_hat[c])))) for c in range(X.shape[1])])
            s_hat = mf + gap
            bound_h = b * b * h_fun(b * lam_hat) * var_hat
            bound_half = 0.5 * b * b * var_hat
            m_exact = s_hat[: n_cut - 1] - s_hat[1:n_cut]
            se_exact = (eb[:, : n_cut - 1] - eb[:, 1:n_cut]).std(axis=0, ddof=1) / math.sqrt(N)
            m_mf = mf[: n_cut - 1] - mf[1:n_cut]
            lam_lim = b * k / v
            m_lim = np.exp(-np.concatenate([[0.0], np.cumsum(lam_lim)[:-1]])) * (-np.expm1(-lam_lim))
            diff = m_exact - m_mf
            lo = -gap[1:n_cut]
            hi = gap[: n_cut - 1]
            # first-order exposure-fluctuation (Jensen) correction, TH-2 Prop. th2:correction:
            #   M_j - M_j^mf = (B^2/2)[e^{-B Lam(s_{j-1})} Var X_{s_{j-1}} - e^{-B Lam(s_j)} Var X_{s_j}] + O(B^3 eps^{3/2})
            q = 0.5 * b * b * mf * var_hat
            corr_sample = q[: n_cut - 1] - q[1:n_cut]
            #   leading-order closed form with Var X_{s_j} = eps D0/(2 sqrt(pi) rho) sum_{i<=j} k_i^2/v_i^3 and Pi's of the limit law
            cum = np.concatenate([[0.0], np.cumsum(k**2 / v**3)])
            pis = np.exp(-np.concatenate([[0.0], np.cumsum(lam_lim)]))
            coef = eps * p.d0 * b * b / (4.0 * math.sqrt(math.pi) * p.rho)
            corr_closed = coef * (pis[:m] * cum[:m] - pis[1 : m + 1] * cum[1 : m + 1])
            rows.append({
                "B": float(b),
                "S_hat_at_checkpoints": s_hat.tolist(),
                "mean_field_survival": mf.tolist(),
                "jensen_gap": gap.tolist(),
                "bound_B2_h_Var": bound_h.tolist(),
                "bound_B2_Var_over_2": bound_half.tolist(),
                "tightness_gap_over_bound_h": np.where(bound_h > 0, gap / np.where(bound_h > 0, bound_h, 1), np.nan).tolist(),
                "sandwich_holds": bool(np.all(gap >= -1e-12) and np.all(gap <= bound_h + 1e-12)),
                "basin_masses_exact_FK": m_exact.tolist(),
                "basin_masses_exact_FK_se": se_exact.tolist(),
                "basin_masses_mean_field": m_mf.tolist(),
                "basin_masses_limit": m_lim.tolist(),
                "exact_minus_limit": (m_exact - m_lim).tolist(),
                "exact_minus_mean_field": diff.tolist(),
                # bracket_holds: gap-identity consistency check M - M^mf = Delta(s_{j-1}) - Delta(s_j)
                #   in [-Delta(s_j), Delta(s_{j-1})] with the EMPIRICAL Jensen gaps (true whenever gap >= 0);
                # bracket_var_holds: the variance-based bounds of Corollary th1:masses(ii),
                #   M - M^mf in [-delta_B(s_j), delta_B(s_{j-1})], delta_B = B^2 h(B Lam) Var X (audit fix TH1-F5).
                "bracket_lo_minus_gap_right": lo.tolist(),
                "bracket_hi_gap_left": hi.tolist(),
                "bracket_holds": bool(np.all(diff >= lo - 1e-12) and np.all(diff <= hi + 1e-12)),
                "bracket_var_lo_minus_delta_right": (-bound_h[1:n_cut]).tolist(),
                "bracket_var_hi_delta_left": bound_h[: n_cut - 1].tolist(),
                "bracket_var_holds": bool(np.all(diff >= -bound_h[1:n_cut] - 1e-12)
                                          and np.all(diff <= bound_h[: n_cut - 1] + 1e-12)),
                "jensen_correction_sample_var": corr_sample.tolist(),
                "jensen_correction_closed_form_leading": corr_closed.tolist(),
                "exact_minus_mf_over_eps": (diff / eps).tolist(),
                "closed_form_over_eps": (corr_closed / eps).tolist(),
                "exact_minus_corrected_mf": (diff - corr_sample).tolist(),
                "pre_window_mass": float(1.0 - s_hat[0]),
                "window_mass_exact": float(s_hat[0] - s_hat[n_cut - 1]),
                "window_mass_limit": float(-math.expm1(-lam_lim.sum())),
                "window_mass_floor_TH1": float(mf[0] - mf[n_cut - 1] - bound_h[n_cut - 1]),
                "post_window_mass_to_t4": float(s_hat[n_cut - 1] - s_hat[-1]),
                "survivors_t4": float(s_hat[-1]),
            })
        # exposure variance at the basin cuts vs asymptotic prediction (meaningful for 'free')
        pred_var = [0.0] + [eps * p.d0 / (2 * math.sqrt(math.pi) * p.rho) * float(np.sum(k[: j + 1] ** 2 / v[: j + 1] ** 3))
                            for j in range(m)]
        slab = np.asarray(d[f"slabexp_{kern}"], float)
        slab_rel_sd = (slab.std(axis=0, ddof=1) / slab.mean(axis=0)).tolist()
        slab_rel_sd_pred = (math.sqrt(1.0 / (2.0 * math.sqrt(math.pi))) * np.sqrt(eps * p.d0 / (p.rho * v))).tolist()
        kern_out[kern] = {
            "Lambda_hat_at_checkpoints": lam_hat.tolist(),
            "Lambda_limit_at_cuts": [0.0] + np.cumsum(k / v).tolist(),
            "Var_X_at_checkpoints": var_hat.tolist(),
            "Var_X_pred_leading_at_cuts": pred_var,
            "Var_X_over_eps_at_cuts": (var_hat[:n_cut] / eps).tolist(),
            "slab_exposure_mean_over_limit": (slab.mean(axis=0) / (k / v)).tolist(),
            "slab_exposure_rel_sd": slab_rel_sd,
            "slab_exposure_rel_sd_pred": slab_rel_sd_pred,
            "budgets": rows,
        }
    out["kernels"] = kern_out
    # time-grid checks on the full kernel: CDF dominance and local peak heights
    t = np.asarray(d["tgrid"], float)
    g = np.asarray(d["G_full"], float)
    lam_t = np.cumsum(g) * dt
    fk = np.asarray(d["FK_full"], float)
    dom, peaks = [], []
    half_gaps = np.diff(np.array(tt)) / 2.0
    for ib, b in enumerate(budgets):
        cdf = np.cumsum(fk[ib])
        margin = (-np.expm1(-b * lam_t)) - cdf
        dom.append({"B": float(b), "min_margin": float(margin.min()), "holds": bool(margin.min() >= -1e-12)})
        f_ex = fk[ib] / dt
        lam_prev = np.concatenate([[0.0], lam_t[:-1]])
        f_mf = b * g * np.exp(-b * lam_prev)
        surv_prev = 1.0
        prow = []
        for j, tj in enumerate(tt):
            left = half_gaps[j - 1] if j > 0 else 0.4
            right = half_gaps[j] if j < m - 1 else 0.4
            sel = (t > tj - left) & (t < tj + right)
            beta = float(b * k[j] / v[j])
            lp = limit_profile_peaks(beta, lam_ratio)
            prow.append({
                "slab": j + 1, "beta": beta,
                "eps_max_f_exact_FK": float(eps * f_ex[sel].max()),
                "eps_max_f_mean_field": float(eps * f_mf[sel].max()),
                "limit_exact_profile_peak": surv_prev * v[j] / p.rho * lp["max_F_beta"],
                "limit_mean_field_profile_peak": surv_prev * v[j] / s_star * lp["max_p_beta"],
                "peak_time_exact_FK": float(t[sel][int(np.argmax(f_ex[sel]))]),
                "peak_time_limit_exact_profile": float(tj + eps * p.rho * lp["argmax_F_beta"] / v[j]),
                "peak_time_limit_mean_field_profile": float(tj + eps * s_star * lp["argmax_p_beta"] / v[j]),
            })
            surv_prev *= math.exp(-beta)
        peaks.append({"B": float(b), "slabs": prow})
    out["cdf_dominance_full"] = dom
    out["local_peak_heights_full"] = peaks
    return out


def opus_sign_check() -> dict:
    """Basin-1 mass of the direct-kill W1 cells versus the mean-field stick-breaking mass
    e^{-B Lam(tau)} - e^{-B Lam(v_1)} (Lam from the D1 free clock; Lam(tau) from the
    exact free-clock quadrature).  TH-1 predicts exact <= mean field + delta(tau)."""
    base_dir = core.UPGRADE_DATA
    mft = json.loads((base_dir / "mean_field_topology.json").read_text())
    fc = {c["label"]: c for c in mft["configurations"]}
    rows = []
    lam_tau_cache = {}
    for f in sorted(glob.glob(str(base_dir / "w1_phase_diagram" / "cell_m*_eps*_B*.json"))):
        dd = json.loads(Path(f).read_text())
        cfg = dd["parameters"]["config"]
        m, eps, b, n = cfg["m"], cfg["eps"], cfg["budget"], cfg["walkers"]
        lab = f"m{m}_eps{eps:g}"
        if lab not in fc:
            continue
        fr = fc[lab]["free_clock"]
        vt, lv = fr["valley_times"], fr["lambda_at_valleys"]
        if len(vt) != m - 1:
            continue
        key = (m, eps, tuple(cfg["weights"]))
        if key not in lam_tau_cache:
            ts = np.linspace(0.0, core.WINDOW[0], 5001)
            gg = core.free_exposure_general(ts, centres_z=core.centres_z_for(m), eps=eps,
                                            weights=tuple(cfg["weights"]), p=core.MODEL)["g"]
            lam_tau_cache[key] = float(np.trapezoid(gg, ts))
        lam_tau = lam_tau_cache[key]
        cl = dd["results"]["classifier"]
        counts, edges = cl["counts"], cl["edges"]
        a_cut, b_cut = edges[0], vt[0]
        s = 0.0
        for i, cnt in enumerate(counts):
            lo, hi = edges[i], edges[i + 1]
            ov = max(0.0, min(hi, b_cut) - max(lo, a_cut))
            s += cnt * ov / (hi - lo)
        meas = s / n
        se = math.sqrt(max(meas * (1 - meas), 1e-300) / n)
        mf1 = math.exp(-b * lam_tau) - math.exp(-b * lv[0])
        rows.append({"cell": Path(f).name, "m": m, "eps": eps, "B": b, "N": n, "window_start": a_cut,
                     "valley_1": b_cut, "Lambda_tau": lam_tau, "Lambda_valley_1": lv[0],
                     "measured_basin1": meas, "measured_se": se, "mean_field_basin1": mf1,
                     "rel_dev": (meas - mf1) / mf1 if mf1 > 0 else None,
                     "measured_le_mf_plus_2se": meas <= mf1 + 2 * se})
    n_ok = sum(r["measured_le_mf_plus_2se"] for r in rows)
    pos = [r for r in rows if r["measured_basin1"] > r["mean_field_basin1"]]
    return {"rows": rows, "n_cells": len(rows), "n_measured_le_mf_plus_2se": n_ok,
            "n_measured_above_mf": len(pos),
            "max_positive_excess_in_se": max(((r["measured_basin1"] - r["mean_field_basin1"]) / r["measured_se"]
                                              for r in pos), default=None)}


def window_accounting() -> dict:
    """TH-9 window accounting from the W1 direct-kill cells (t_max = 4, 1e6 walkers):
    kills before tau = 0.5, inside [0.5, 3.5], after 3.5 up to 4, survivors at 4, with the
    TH-9 bounds  P(T_R <= tau) <= B Lam(tau)  and  P(3.5 < T_R <= 4) <= B (Lam(4) - Lam(3.5))."""
    base_dir = core.UPGRADE_DATA
    rows = []
    cache = {}
    for f in sorted(glob.glob(str(base_dir / "w1_phase_diagram" / "cell_m*_eps*_B*.json"))):
        if "refined" in f:
            continue
        dd = json.loads(Path(f).read_text())
        cfg = dd["parameters"]["config"]
        res = dd["results"]
        m, eps, b, n = cfg["m"], cfg["eps"], cfg["budget"], cfg["walkers"]
        key = (m, eps, tuple(cfg["weights"]))
        if key not in cache:
            ts_pre = np.linspace(0.0, core.WINDOW[0], 4001)
            ts_post = np.linspace(core.WINDOW[1], 4.0, 4001)
            g_pre = core.free_exposure_general(ts_pre, centres_z=core.centres_z_for(m), eps=eps,
                                               weights=tuple(cfg["weights"]), p=core.MODEL)["g"]
            g_post = core.free_exposure_general(ts_post, centres_z=core.centres_z_for(m), eps=eps,
                                                weights=tuple(cfg["weights"]), p=core.MODEL)["g"]
            cache[key] = (float(np.trapezoid(g_pre, ts_pre)), float(np.trapezoid(g_post, ts_post)))
        lam_tau, lam_post = cache[key]
        full = res["histograms"]["linear_full_range"]
        fe, fc = full["edges"], full["counts"]
        cl = res["classifier"]
        pre = 0
        for i, cnt in enumerate(fc):
            if fe[i + 1] <= 0.48 + 1e-12:
                pre += cnt
            elif abs(fe[i] - 0.48) < 1e-9:
                pre += cnt - cl["counts"][0]
        kills, inside = res["kills"], res["kills_in_window"]
        post = kills - inside - pre
        rows.append({"cell": Path(f).name, "m": m, "eps": eps, "B": b, "N": n,
                     "frac_before_tau": pre / n, "frac_inside": inside / n, "frac_after_T_to_4": post / n,
                     "frac_survivors_t4": res["survivors"] / n,
                     "bound_before_tau_B_Lambda_tau": b * lam_tau,
                     "bound_after_T_to_4_B_dLambda": b * lam_post,
                     "Lambda_tau": lam_tau, "Lambda_4_minus_Lambda_T": lam_post})
    viol = [r["cell"] for r in rows
            if r["frac_after_T_to_4"] > r["bound_after_T_to_4_B_dLambda"] + 3 * math.sqrt(max(r["bound_after_T_to_4_B_dLambda"], 1e-12) / r["N"]) + 5.0 / r["N"]]
    viol_pre = [r["cell"] for r in rows
                if r["frac_before_tau"] > r["bound_before_tau_B_Lambda_tau"] + 3 * math.sqrt(max(r["bound_before_tau_B_Lambda_tau"], 1e-12) / r["N"]) + 5.0 / r["N"]]
    excess_pre = [{"cell": r["cell"], "frac_before_tau": r["frac_before_tau"], "bound": r["bound_before_tau_B_Lambda_tau"],
                   "excess_in_poisson_sd": (r["frac_before_tau"] - r["bound_before_tau_B_Lambda_tau"]) * r["N"]
                   / math.sqrt(max(r["bound_before_tau_B_Lambda_tau"] * r["N"], 1.0))}
                  for r in rows if r["frac_before_tau"] > r["bound_before_tau_B_Lambda_tau"]]
    return {"rows": rows, "n_cells": len(rows), "cells_violating_post_window_bound_beyond_noise": viol,
            "cells_violating_pre_window_bound_beyond_noise": viol_pre,
            "cells_with_pre_window_fraction_above_bound": excess_pre,
            "note": "bounds hold for the continuous-time law; the direct-kill data carry Poisson noise and O(dt) bias"}


def _slab_mean_occupation(i_centre: float, a: float, b: float, eps: float, p, n: int = 40001) -> float:
    """Ungated mean occupation J_i(a, b) = int_a^b phi_{eps S_*}(mu(u) - mu_i) du of a unit-weight slab
    (stationary midpoint variance); it bounds the gated occupation from above."""
    if b <= a:
        return 0.0
    u = np.linspace(a, b, n)
    mu_u = p.z_bar + (p.z0 - p.z_bar) * np.exp(-p.gamma * u)
    s = eps * math.sqrt(p.d0 / (2 * p.gamma) + p.rho**2)
    dens = np.exp(-0.5 * ((mu_u - i_centre) / s) ** 2) / (math.sqrt(2 * math.pi) * s)
    return float(np.trapezoid(dens, u))


def allocation_design_check(cache: Path, p) -> dict:
    """TH-4 at finite noise: FK basin masses of the max-min design w*(B), obtained by reweighting the
    stored per-slab exposure TOTALS on (0, 4] (equal-weight ensembles):
        X_sur(j) = sum_{i<=j} (w_i / w_i^sim) * slabexp_i,   j = 1..m.
    This is a SURROGATE (audit fix TH4-F3): it evaluates the partition P' = (0, s_1], ..., (s_{m-1}, 4]
    (first basin from t = 0, last basin extended from 3.5 to 4 -- per-slab exposures at the cuts are not
    stored), and at each interior cut s_j it mis-assigns the part of slab i's exposure accrued after s_j
    (i <= j) or before s_j (i > j).  For the designed weights we report the deterministic bound
        |M_j^sur - M_j(P')| <= b_{j-1} + b_j,  b_j = (B/A) [sum_{i<=j} w_i J_i(s_j, 4) + sum_{i>j} w_i J_i(0, s_j)],
    b_0 = b_m = 0, with the ungated mean occupations J_i (|E e^{-B x} - E e^{-B y}| <= B E|x - y|).
    At equal weights the exact P' masses are available from the stored checkpoints (0, valleys, 4) and
    give the realised interior mis-assignment.  Masses at the original cuts (0.5, valleys, 3.5) for
    reweighted designs need per-slab exposures at the cuts (plan item N1).  Only eps <= 0.05."""
    import fb_allocation_law as alloc

    rows = []
    for m, eps in ((2, 0.05), (2, 0.035), (3, 0.05), (3, 0.035)):
        path = cache / f"fk_m{m}_e{eps:g}.npz"
        if not path.exists():
            continue
        d = np.load(path)
        w_sim = np.asarray(d["weights"], float)
        v = alloc.speeds(core.TARGET_TIMES[m], p)
        area = alloc.area_factor(p)
        ckp = np.asarray(d["checkpoints"], float)  # 0.5, valleys (m-1), 3.5, 4.0
        valleys = ckp[1:m]
        t_end = float(ckp[-1])
        centres = np.asarray(d["centres"], float)  # mu(t_j)
        occ_after = np.array([[_slab_mean_occupation(centres[i], valleys[j], t_end, eps, p) for i in range(m)]
                              for j in range(m - 1)])  # J_i(s_j, 4)
        occ_before = np.array([[_slab_mean_occupation(centres[i], 0.0, valleys[j], eps, p) for i in range(m)]
                               for j in range(m - 1)])  # J_i(0, s_j)
        for kern in ("full", "free"):
            slab = np.asarray(d[f"slabexp_{kern}"], float)
            lamck = np.asarray(d[f"lamck_{kern}"], float)
            # consistency of the reweighting surrogate at the simulated (equal) weights:
            # mean |X_surrogate(s_j) - X(s_j)| per cut (the last cut uses slab totals to t=4)
            surrogate_eq = np.cumsum(slab, axis=1)
            cons = [float(np.mean(np.abs(surrogate_eq[:, j] - lamck[:, j + 1]))) for j in range(m)]
            for b in (1.0, 2.0, 4.0, 8.0):
                opt = alloc.p_star(b, v, area)
                w = np.asarray(opt["weights"], float)
                x = np.cumsum(slab * (w / w_sim)[None, :], axis=1)  # X(s_j), j=1..m
                surv = np.concatenate([np.ones((x.shape[0], 1)), np.exp(-b * x)], axis=1)
                masses = (surv[:, :-1] - surv[:, 1:]).mean(axis=0)
                se = (surv[:, :-1] - surv[:, 1:]).std(axis=0, ddof=1) / math.sqrt(x.shape[0])
                eqm = alloc.masses(b, list(w_sim), v, area)
                x_eq = np.cumsum(slab, axis=1)
                surv_eq = np.concatenate([np.ones((x_eq.shape[0], 1)), np.exp(-b * x_eq)], axis=1)
                masses_eq = (surv_eq[:, :-1] - surv_eq[:, 1:]).mean(axis=0)
                cuts = np.concatenate([np.ones((lamck.shape[0], 1)), np.exp(-b * lamck[:, 1 : m + 1])], axis=1)
                masses_eq_true = (cuts[:, :-1] - cuts[:, 1:]).mean(axis=0)
                # exact equal-weight masses of the surrogate partition P' = (0, s_1], ..., (s_{m-1}, 4]
                cuts_p = np.concatenate([np.ones((lamck.shape[0], 1)), np.exp(-b * lamck[:, 1:m]),
                                         np.exp(-b * lamck[:, [m + 1]])], axis=1)
                masses_eq_p = (cuts_p[:, :-1] - cuts_p[:, 1:]).mean(axis=0)

                def cut_bound(ww):
                    bj = [0.0]
                    for j in range(m - 1):  # interior cut s_{j+1} (0-based j)
                        mis = sum(ww[i] * occ_after[j, i] for i in range(j + 1)) + \
                            sum(ww[i] * occ_before[j, i] for i in range(j + 1, m))
                        bj.append(b * mis / area)
                    bj.append(0.0)
                    return [bj[j] + bj[j + 1] for j in range(m)], bj[1:m]

                mass_bound_designed, cut_bound_designed = cut_bound(w)
                mass_bound_eq, _ = cut_bound(w_sim)
                rows.append({"m": m, "eps": eps, "kernel": kern, "B": b, "w_opt": w.tolist(),
                             "p_star": opt["p_star"],
                             # NB: key kept for continuity; these are SURROGATE estimates for partition P'
                             "exact_masses_designed": masses.tolist(),
                             "exact_masses_designed_se": se.tolist(),
                             "max_abs_dev_from_p_star": float(np.max(np.abs(masses - opt["p_star"]))),
                             "exact_min_mass_designed": float(masses.min()),
                             "surrogate_partition": "(0, s_1], ..., (s_{m-1}, 4]",
                             "surrogate_interior_cut_misassignment_bound_designed": mass_bound_designed,
                             "surrogate_interior_cut_exposure_bound_designed_B_times": cut_bound_designed,
                             "surrogate_interior_cut_misassignment_bound_equal_weights": mass_bound_eq,
                             "exact_masses_equal_weights": masses_eq.tolist(),
                             "limit_masses_equal_weights": eqm,
                             "exact_min_mass_equal_weights": float(masses_eq.min()),
                             "equal_weight_masses_true_cuts": masses_eq_true.tolist(),
                             "equal_weight_masses_partition_P_prime": masses_eq_p.tolist(),
                             "surrogate_minus_exact_P_prime_equal_weights": (masses_eq - masses_eq_p).tolist(),
                             "surrogate_bias_equal_weights": (masses_eq - masses_eq_true).tolist(),
                             "surrogate_consistency_mean_abs": cons})
    return {"rows": rows, "method": allocation_design_check.__doc__}


def free_clock_outside_window(t_max: float = 20.0, dt_grid: float = 0.005) -> dict:
    """TH-9: sign of G' outside the window I = [0.5, 3.5] for the anchor designs (equal weights),
    computed in the log domain: ln G = ln c(t) + ln a0 + logsumexp_j(ln w_j - (x(t)-c_j)^2/(2 sigma^2)),
    with the frozen contact quadrature of validate_exact_m_offlattice.py (d = 2).  Reports the number of
    sign changes of (ln G)' on the sampled parts [0.02, tau] and [T, t_max] of the grid
    ts = 0.02:dt_grid:t_max, with (ln G)' from np.gradient (second-order centred differences), the first
    grid time after T at which (ln G)' >= 0 (if any), and max_{[T, t_max]} G / max_I G.  These are
    finite-grid observations: off-grid zeros and (0, 0.02) are not covered."""
    import validate_exact_m_offlattice as base

    p = core.MODEL
    rows = []
    ts = np.arange(0.02, t_max + 1e-12, dt_grid)
    for m in (2, 3):
        cz = core.centres_z_for(m)
        sgn = base.sign_mu_prime(p)
        cx = sgn * np.asarray(cz, float) / p.ell0
        w = np.full(m, 1.0 / m)
        for eps in (0.05, 0.1, 0.2):
            sigma = base.mixture_sigma(eps, p)
            c_vals = np.concatenate([base.contact_probability(ts[k:k + 400], eps, p) for k in range(0, ts.size, 400)])
            x = np.asarray(base.x_of_t(ts, p), float)
            e = np.log(w)[:, None] - (x[None, :] - cx[:, None]) ** 2 / (2 * sigma**2)
            emax = e.max(axis=0)
            log_h = emax + np.log(np.exp(e - emax).sum(axis=0))
            log_a0 = -math.log(p.torus_w ** (p.dim - 1) * math.sqrt(2 * math.pi) * eps
                               * math.sqrt(p.d0 / (2 * p.gamma) + p.rho**2))
            log_g = np.log(np.maximum(c_vals, 1e-300)) + log_a0 + log_h
            dlog = np.gradient(log_g, ts)
            tau, t_end = core.WINDOW
            pre = (ts <= tau)
            post = (ts >= t_end)
            win = (ts >= tau) & (ts <= t_end)

            def n_changes(mask):
                sgnv = np.sign(dlog[mask])
                return int(np.sum(sgnv[1:] * sgnv[:-1] < 0))

            post_idx = np.flatnonzero(post & (dlog >= 0))
            rows.append({
                "m": m, "eps": eps, "t_grid": [float(ts[0]), float(ts[-1]), dt_grid],
                "sign_changes_pre_window": n_changes(pre),
                "min_dlogG_pre_window": float(dlog[pre].min()),
                "sign_changes_post_window": n_changes(post),
                "max_dlogG_post_window": float(dlog[post].max()),
                "first_t_after_T_with_dlogG_nonneg": (float(ts[post_idx[0]]) if post_idx.size else None),
                "log10_max_G_post_over_max_G_window": float((log_g[post].max() - log_g[win].max()) / math.log(10)),
                "contact_at_t_max": float(c_vals[-1]),
            })
    return {"rows": rows}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--fk-cache", default=os.environ.get("FB_FK_CACHE", str(FK_CACHE_DEFAULT)))
    args = ap.parse_args()
    cache = Path(args.fk_cache)
    p = core.MODEL
    cases = []
    for m, eps in CASES:
        path = cache / f"fk_m{m}_e{eps:g}.npz"
        if not path.exists():
            cases.append({"m": m, "eps": eps, "missing": str(path)})
            continue
        cases.append(analyse_case(path, p))
        print("done", path.name, flush=True)
    payload = {
        "schema_version": 1,
        "item": "TH-1/TH-2 numerical checks from stored FK ensembles (no new simulation)",
        "fk_cache": str(cache),
        "fk_generator": "notes/gap_diagnosis_20260923/theory_scout/fk_paths.py (seed per file, dt=1e-3, 2e5 paths)",
        "model": core.model_payload(p),
        "cases": cases,
        "basin1_sign_check_w1": opus_sign_check(),
        "window_accounting_w1": window_accounting(),
        "allocation_design_check": allocation_design_check(cache, p),
        "free_clock_outside_window": free_clock_outside_window(),
    }
    core.write_json(OUT_JSON, payload)
    print("wrote", OUT_JSON)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
